// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgIhvhw_yCt58-P8ArYydiCTGpJURfEhc',
    appId: '1:401965662857:web:c0651cf4c8b6e344d4bc58',
    messagingSenderId: '401965662857',
    projectId: 'mytodo-7fb64',
    authDomain: 'mytodo-7fb64.firebaseapp.com',
    storageBucket: 'mytodo-7fb64.firebasestorage.app',
    measurementId: 'G-6KLB8WTQYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC16mI2PdVibA3A6G3LZwWCimzR6FACXAs',
    appId: '1:401965662857:android:829177ac87038614d4bc58',
    messagingSenderId: '401965662857',
    projectId: 'mytodo-7fb64',
    storageBucket: 'mytodo-7fb64.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO65Nd5gO4Ad0XfwpoNu85b7dJUX6SICM',
    appId: '1:401965662857:ios:97b6ae30835626b6d4bc58',
    messagingSenderId: '401965662857',
    projectId: 'mytodo-7fb64',
    storageBucket: 'mytodo-7fb64.firebasestorage.app',
    iosBundleId: 'com.example.myTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO65Nd5gO4Ad0XfwpoNu85b7dJUX6SICM',
    appId: '1:401965662857:ios:97b6ae30835626b6d4bc58',
    messagingSenderId: '401965662857',
    projectId: 'mytodo-7fb64',
    storageBucket: 'mytodo-7fb64.firebasestorage.app',
    iosBundleId: 'com.example.myTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgIhvhw_yCt58-P8ArYydiCTGpJURfEhc',
    appId: '1:401965662857:web:3cb79fd37ef903a6d4bc58',
    messagingSenderId: '401965662857',
    projectId: 'mytodo-7fb64',
    authDomain: 'mytodo-7fb64.firebaseapp.com',
    storageBucket: 'mytodo-7fb64.firebasestorage.app',
    measurementId: 'G-0BD6Y8V4ZT',
  );
}
